'use strict';

angular.module('app.common.stopwords', []);

//Lista com as stopwords em português.
angular.module('app.common.stopwords').constant('stopwords-pt', [
    'a', 'a', 'agora', 'ainda', 'alguem', 'algum', 'alguma', 'algumas', 'alguns', 'ampla', 'amplas', 'amplo', 'amplos', 'ante', 'antes', 'ao', 'aos', 'apos', 'aquela', 'aquelas', 'aquele', 'aqueles', 'aquilo', 'as', 'ate', 'atraves', 'cada', 'coisa', 'coisas', 'com', 'como', 'contra', 'contudo', 'da', 'daquele', 'daqueles', 'das', 'de', 'dela', 'delas', 'dele', 'deles', 'depois', 'dessa', 'dessas', 'desse', 'desses', 'desta', 'destas', 'deste', 'deste', 'destes', 'deve', 'devem', 'devendo', 'dever', 'devera', 'deverao', 'deveria', 'deveriam', 'devia', 'deviam', 'disse', 'disso', 'disto', 'dito', 'diz', 'dizem', 'do', 'dos', 'e', 'e', 'e', 'ela', 'elas', 'ele', 'eles', 'em', 'enquanto', 'entre', 'era', 'essa', 'essas', 'esse', 'esses', 'esta', 'esta', 'estamos', 'estao', 'estas', 'estava', 'estavam', 'estavamos', 'este', 'estes', 'estou', 'eu', 'fazendo', 'fazer', 'feita', 'feitas', 'feito', 'feitos', 'foi', 'for', 'foram', 'fosse', 'fossem', 'grande', 'grandes', 'ha', 'isso', 'isto', 'ja', 'la', 'la', 'la', 'lhe', 'lhes', 'lo', 'mas', 'me', 'mesma', 'mesmas', 'mesmo', 'mesmos', 'meu', 'meus', 'minha', 'minhas', 'muita', 'muitas', 'muito', 'muitos', 'na', 'nao', 'nas', 'nem', 'nenhum', 'nessa', 'nessas', 'nesta', 'nestas', 'ninguem', 'no', 'nos', 'nos', 'nossa', 'nossas', 'nosso', 'nossos', 'num', 'numa', 'nunca', 'o', 'os', 'ou', 'outra', 'outras', 'outro', 'outros', 'para', 'pela', 'pelas', 'pelo', 'pelos', 'pequena', 'pequenas', 'pequeno', 'pequenos', 'per', 'perante', 'pode', 'pode', 'podendo', 'poder', 'poderia', 'poderiam', 'podia', 'podiam', 'pois', 'por', 'porem', 'porque', 'posso', 'pouca', 'poucas', 'pouco', 'poucos', 'primeiro', 'primeiros', 'propria', 'proprias', 'proprio', 'proprios', 'quais', 'qual', 'quando', 'quanto', 'quantos', 'que', 'quem', 'sao', 'se', 'seja', 'sejam', 'sem', 'sempre', 'sendo', 'sera', 'serao', 'seu', 'seus', 'si', 'sido', 'so', 'sob', 'sobre', 'sua', 'suas', 'talvez', 'tambem', 'tampouco', 'te', 'tem', 'tendo', 'tenha', 'ter', 'teu', 'teus', 'ti', 'tido', 'tinha', 'tinham', 'toda', 'todas', 'todavia', 'todo', 'todos', 'tu', 'tua', 'tuas', 'tudo', 'última', 'ultimas', 'ultimo', 'ultimos', 'um', 'uma', 'umas', 'uns', 'vendo', 'ver', 'vez', 'vindo', 'vir', 'vos', 'vos'
]);

//Lista com as stopwords em inglês.
angular.module('app.common.stopwords').constant('stopwords-en', [
    'a', 'about', 'above', 'according', 'across', 'actually', 'after', 'again', 'against', 'all', 'almost', 'along', 'already', 'also', 'although', 'always', 'among', 'an', 'and', 'another', 'any', 'anything', 'are', 'aren', 'as', 'at', 'away', 'back', 'back', 'be', 'because', 'been', 'before', 'behind', 'being', 'below', 'besides', 'better', 'between', 'beyond', 'both', 'but', 'by', 'can', 'certain', 'could', 'do', 'does', 'during', 'each', 'else', 'enough', 'even', 'ever', 'few', 'for', 'from', 'further', 'get', 'going', 'got', 'great', 'has', 'have', 'he', 'her', 'here', 'high', 'his', 'how', 'however', 'i', 'if', 'in', 'instead', 'into', 'is', 'it', 'its', 'itself', 'just', 'later', 'least', 'less', 'less', 'let', 'little', 'many', 'may', 'maybe', 'me', 'might', 'more', 'most', 'much', 'must', 'neither', 'never', 'new', 'no', 'non', 'nor', 'not', 'nothing', 'of', 'off', 'often', 'old', 'on', 'once', 'one', 'only', 'or', 'other', 'our', 'out', 'over', 'perhaps', 'put', 'rather', 'really', 'set', 'several', 'she', 'should', 'since', 'snot', 'snt', 'so', 'some', 'something', 'sometimes', 'soon', 'still', 'such', 't', 'than', 'that', 'the', 'their', 'them', 'then', 'there', 'therefore', 'these', 'they', 'thing', 'this', 'those', 'though', 'three', 'through', 'till', 'to', 'together', 'too', 'toward', 'towards', 'two', 'under', 'up', 'upon', 'us', 'very', 'very', 'was', 'were', 'what', 'when', 'where', 'whether', 'which', 'while', 'whole', 'whose', 'will', 'with', 'within', 'without', 'would', 'yet', 'you', 'your'
]);

//Lista com as stopwords em espanhol.
angular.module('app.common.stopwords').constant('stopwords-es', [
    'a', 'aca', 'adelante', 'ademas', 'ahi', 'ahora', 'al', 'alguna', 'algunas', 'alguno', 'algunos', 'as', 'asi', 'aun', 'bastante', 'bien', 'cada', 'como', 'con', 'cosa', 'cosas', 'cual', 'cual', 'cuales', 'cuales', 'cuando', 'da', 'de', 'debe', 'debemos', 'del', 'dentro', 'desde', 'despues', 'donde', 'dos', 'durante', 'e', 'el', 'ellos', 'en', 'entonces', 'entre', 'era', 'eran', 'es', 'esa', 'esas', 'ese', 'eso', 'esos', 'esta', 'esta', 'estaba', 'estaban', 'estamos', 'estan', 'estar', 'estas', 'este', 'esto', 'estos', 'frente', 'fue', 'fuera', 'fueron', 'ha', 'haber', 'habia', 'hace', 'hacen', 'hacer', 'hacia', 'haciendo', 'han', 'hasta', 'hay', 'hecho', 'hoy', 'la', 'las', 'le', 'les', 'lo', 'los', 'me', 'mientras', 'misma', 'mismas', 'mismo', 'mismos', 'mucha', 'muchas', 'mucho', 'muchos', 'muy', 'ni', 'no', 'nos', 'nuestra', 'nuestras', 'nuestro', 'nuestros', 'o', 'o', 'os', 'otra', 'otras', 'otro', 'otros', 'para', 'pero', 'podemos', 'podria', 'por', 'porque', 'puede', 'pueden', 'pues', 'que', 'qué', 'se', 'sea', 'según', 'segundo', 'ser', 'seria', 'si', 'sido', 'siendo', 'sobre', 'solamente', 'son', 'su', 'tal', 'tambien', 'tan', 'tanto', 'tenemos', 'tener', 'tenian', 'tiene', 'tienen', 'toda', 'todas', 'todavia', 'todo', 'todos', 'traves', 'un', 'una', 'uno', 'va', 'vamos', 'van', 'veces', 'vemos', 'ver', 'vez', 'y', 'ya'
]);